### ISSUE TITLE
invite register page

### ISSUE THREAD

**Issue by loeffelr** [go-saas/go-saas-ui#26]
![Screenshot 2020-09-16 at 11 19 23](https://user-images.githubusercontent.com/38214863/93318045-7edf1080-f80e-11ea-9ed6-cc69e749f9f9.png)

when no account is registered with the email that has been invited

logo on top
width like login

page name: invitation
layout name: 

after register:
green notice that register was successfull --> go to login

**Comment by loeffel-io** [comment]
ey bzgl dem anderen layout
14:54 Uhr
lass einfach das master layout verwenden mit der navi
14:54 Uhr
das passt schon so eig
14:54 Uhr
können wir uns den aufwand sparen
14:54 Uhr
und dann in die config meta einfach guest: true

**Comment by loeffel-io** [comment]
2x passwort

**Comment by loeffelr** [comment]
checkbox accept terms of service etc.
