### ISSUE TITLE
accept email after register

### ISSUE THREAD

**Issue by loeffel-io** [go-saas/go-saas-ui#50]
komplette page designen

**Comment by loeffel-io** [comment]
auth middleware einfach wenn nicht aktiviert dann auf "email aktivieren" seite

**Comment by loeffelr** [comment]
1. Page: Login --> Du hast deine Email noch nicht bestätigt
2. Page: Email Button --> Du hast deine Email erfolgreich bestätigt!

Bestätigt --> Refresh --> Dashboard

**Comment by loeffel-io** [comment]
page name für unverifzierte email nach login: email-unverified (bearbeitet) 
16:58 Uhr
page name für aktivierung: email-verification

**Comment by loeffel-io** [comment]
https://github.com/go-saas/go-saas/blob/master/email_verification.go#L12

**Comment by loeffelr** [comment]
<img width="1110" alt="Bildschirmfoto 2020-09-29 um 16 51 52" src="https://user-images.githubusercontent.com/38214863/94579045-ae633380-0278-11eb-8cbc-f6f5e197b5b4.png">

**Comment by loeffel-io** [comment]
https://github.com/go-saas/go-saas/blob/master/email_verification.go#L46

**Comment by loeffel-io** [comment]
ticket ist ready to go 🚀
