### ISSUE TITLE
WIP: refactor leave delete team 

### ISSUE THREAD

**Issue by loeffel-io** [go-saas/go-saas-ui#52]
split

**Comment by loeffelr** [comment]
bitte mehr details

**Comment by loeffel-io** [comment]
kommt noch - muss erst die apis machen

**Comment by loeffel-io** [comment]
https://localhost/settings/team/user
team user liste hat sich geändert - aus _users_ wurden jetzt _team users_
https://github.com/go-saas/go-saas/blob/master/team_user_team.go#L14

**Comment by loeffel-io** [comment]
bei dem user select: https://github.com/go-saas/go-saas-ui/blob/master/src/components/selects/team/User.vue wurde jetzt auch aus user => teamUser (datei muss auch unbenannt werden etc)
https://github.com/go-saas/go-saas/blob/master/team_user_team.go#L14

**Comment by loeffel-io** [comment]
leaveDelete route wurde aufgesplittet: 

@ user => teams => delete - das ist jetzt team delete: https://github.com/go-saas/go-saas/blob/master/team.go#L141

@ user => teams => leave - das ist jetzt immer noch "Leave" aber im hintergrund ein teamUser delete: https://github.com/go-saas/go-saas/blob/master/team_user.go#L12

**Comment by loeffel-io** [comment]
Und einen user löschen @ team => users => delete ist jetzt ein teamUserTeam Delete: https://github.com/go-saas/go-saas/blob/master/team_user_team.go#L41

**Comment by loeffel-io** [comment]
@ team => users => invite hat sich einiges geändert: https://github.com/go-saas/go-saas/pull/13/files#diff-15933918f02917e84b72bb5cab445aecR47
