### ISSUE TITLE
Renaming registration to register

### ISSUE THREAD

**Issue by loeffel-io** [go-saas/go-saas-ui#64]
wir haben nirgends das wort registration ^^

**Comment by loeffelr** [comment]
Invitation
Registration
Navigation
?
Ich folge nur dem Muster

**Comment by loeffel-io** [comment]
ja ist schwer, gibt ja auch passwort-reset bspw 
bei register ist das einer dieser sonderfälle finde ich - spark hat auch register und alle unseren routen etc heißen register 
deshalb lass und das bitte register nennen 
müssen halt in so fällen dann einfach nochmal kurz schnacken

**Comment by loeffelr** [comment]
warum dann "^^"? 
ich checks nicht

**Comment by loeffelr** [comment]
schreib halt vorher ins ticket genau wie die kacke heißen soll dann muss ichs nicht 10 mal ändern
weil egal wie ichs mach es ist ja scheinbar nie die richtige wahl :D

**Comment by loeffel-io** [comment]
na wenn wir bspw nicht einmal das wort iwo verwenden, dass du verwenden möchtest, sollten wir einfach kurz drüber sprechen 👍
